"""Create the stock tracker tables in the configured Supabase database."""

import sys
from pathlib import Path

from sqlalchemy import text

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from utils.supabase_data_manager import SupabaseDataManager


SCHEMA_STATEMENTS = (
    """
    create table if not exists holdings (
      id bigint generated by default as identity primary key,
      account text not null,
      stock_name text not null,
      stock_symbol text not null,
      quantity integer not null default 0,
      average_price_per_share numeric(18, 6) not null default 0,
      capital_gain_loss numeric(18, 2) not null default 0,
      date_of_acquisition date,
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      unique (account, stock_symbol)
    )
    """,
    """
    create table if not exists trades (
      id bigint generated by default as identity primary key,
      account text not null,
      stock_name text not null,
      stock_symbol text not null,
      date_of_trade date,
      trade_type text not null check (trade_type in ('B', 'S', 'T')),
      shares_traded integer not null check (shares_traded > 0),
      price_per_share numeric(18, 6) not null,
      commission numeric(18, 2) not null default 0,
      cost numeric(18, 2),
      gross_proceeds numeric(18, 2),
      net_proceeds numeric(18, 2),
      average_cost_at_sale numeric(18, 6),
      capital_gain_loss numeric(18, 2),
      created_at timestamptz not null default now()
    )
    """,
    "alter table trades alter column date_of_trade drop not null",
)


def main() -> int:
    manager = SupabaseDataManager()
    with manager.engine.begin() as connection:
        for statement in SCHEMA_STATEMENTS:
            connection.execute(text(statement))
    print("Supabase schema is ready: holdings, trades")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
